#!/bin/bash
clear

##this script print different pattern

echo -e "\ndiamond pattern\n"

#first pattern starts from here it print pattern like this:
#*
#**
#***
#****
#*****
#****
#***
#**
#*

for (( a=1;$a<=5;a++ ))
do
	for (( b=1;$b<=$a;b++ ))
	do
		echo -n "*"
	done
echo " "
done

for (( a=1;$a<=5;a++ ))
do
	for (( b=$a;$b<=4;b++ ))
	do
		echo -n "*"
	done
echo " "
done

#first pattern end here


echo -e "\n\npyramid pattern\n"

#second pattern starts from here it print pattern like this:
#    *
#   ***
#  *****
# *******
#*********

for (( a=1;$a<=5;a++ ))
do
	for (( b=$a;$b<=5;b++ ))
	do
		echo -n " "
	done
	for (( b=1;$b<=$a;b++ ))
	do
		echo -n "*"
	done
	
	for (( b=2;$b<=$a;b++ ))
	do
		echo -n "*"
	done
	
	
echo " "
done
#second pattern end here

echo -e "\n\nright slanting cube pattern\n"
#third pattern starts from here it print pattern like this:
#     ****** 
#    ****** 
#   ****** 
#  ****** 
# ****** 

for (( a=1;$a<=5;a++ ))
do
	for (( b=$a;$b<=5;b++ ))
	do
		echo -n " "
	done
	for (( b=1;$b<=$a;b++ ))
	do
		echo -n "*"
	done
	
	for (( b=$a;$b<=5;b++ ))
	do
		echo -n "*"
	done
	
	
echo " "
done
#third pattern end here

echo -e "\n\nspotlight pattern\n"
#fourth pattern starts from here it print pattern like this:
#  * 
#   *** 
#    ***** 
#     ******* 
#      ********* 


for (( a=1;$a<=5;a++ ))
do
	for (( b=1;$b<=$a;b++ ))
	do
		echo -n " "
	done
	for (( b=1;$b<=$a;b++ ))
	do
		echo -n "*"
	done
	
	for (( b=2;$b<=$a;b++ ))
	do
		echo -n "*"
	done
	
	
echo " "
done
#fourth pattern end here

echo -e "\n\nleft slanting cube pattern\n"
#fourth pattern starts from here it print pattern like this:
#     ****** 
#    ****** 
#   ****** 
#  ****** 
# ****** 


for (( a=1;$a<=5;a++ ))
do
	for (( b=$a;$b<=5;b++ ))
	do
		echo -n " "
	done
	for (( b=1;$b<=$a;b++ ))
	do
		echo -n "*"
	done
	
	for (( b=$a;$b<=5;b++ ))
	do
		echo -n "*"
	done
	
	
echo " "
done
#fourth pattern end here



echo -e "\n\nreverse  pattern\n"
#fifth pattern starts from here it print pattern like this:
# ********* 
#  ******* 
#   ***** 
#    *** 
#     * 
for (( a=1;$a<=5;a++ ))
do
	for (( b=1;$b<=$a;b++ ))
	do
		echo -n " "
	done
	for (( b=$a;$b<=5;b++ ))
	do
		echo -n "*"
	done
	
	for (( b=$a;$b<=4;b++ ))
	do
		echo -n "*"
	done
	
	
echo " "
done

#fifth pattern end here
